name: edgehead
version: 2.0.0
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_collection: ^3.1.3
  built_value: ^5.5.5
  cli_menu: ^0.2.1
  egamebook_builder:
    path: ../egamebook_builder
  meta: ^1.1.6
  logging: ^0.11.3
  path: ^1.6.2
  quiver: ^2.0.0+1
  slot_machine: ^5.0.1

dev_dependencies:
  args: ^1.5.0
  build_runner: ^0.10.1
  built_value_generator: '>=5.0.0 <7.0.0'
  test: ^1.3.0
