# Created with package:mono_repo v2.3.0
language: dart

jobs:
  include:
    - stage: smoke_test
      name: "SDK: stable; PKG: edgehead; TASKS: dartfmt && dartanalyzer"
      dart: stable
      os: linux
      env: PKGS="edgehead"
      script: ./tool/travis.sh dartfmt dartanalyzer
    - stage: smoke_test
      name: "SDK: stable; PKG: egamebook_builder; TASKS: dartfmt && dartanalyzer"
      dart: stable
      os: linux
      env: PKGS="egamebook_builder"
      script: ./tool/travis.sh dartfmt dartanalyzer
    - stage: build
      name: "SDK: stable; PKG: edgehead; TASKS: `pub run build_runner build --delete-conflicting-outputs`"
      dart: stable
      os: linux
      env: PKGS="edgehead"
      script: ./tool/travis.sh command_0
    - stage: unit_test
      name: "SDK: stable; PKG: edgehead; TASKS: [`pub run test`, `pub run test -t long-running --run-skipped`]"
      dart: stable
      os: linux
      env: PKGS="edgehead"
      script: ./tool/travis.sh command_1 command_2
    - stage: unit_test
      name: "SDK: stable; PKG: egamebook_builder; TASKS: `pub run test`"
      dart: stable
      os: linux
      env: PKGS="egamebook_builder"
      script: ./tool/travis.sh command_1

stages:
  - smoke_test
  - build
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - egamebook_builder/.dart_tool/build
