name: egamebook
version: 0.1.0
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  a_star: any
  analyzer: "0.25.0+1"
  args: any
  browser: any
  html: any
  jsonml: any
  markdown: any
  path: any
  test: any
  watcher: any
  logging: any
  quiver: any
  ansicolor: "^0.0.9"
  resource: any
executables:
  egamebook:
