name: egamebook
version: 0.1.2
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  a_star: ^0.3.0
  analyzer: ^0.25.0+1
  args: ^0.13.4+2
  browser: ^0.10.0+2
  html: ^0.12.2+2
  jsonml: ^0.1.7
  markdown: ^0.10.1
  path: ^1.3.9
  test: ^0.12.14+1
  watcher: ^0.9.7+2
  logging: ^0.11.3
  quiver: ^0.22.0
  ansicolor: ^0.0.9
  resource: ^1.1.0
executables:
  egamebook:
