name: egamebook
version: 1.0.0-dev.1
author: Filip Hracek <filip.hracek@gmail.com>

dependencies:
  analyzer: ">=0.25.0+1 <1.0.0"
  ansicolor: ^0.0.9
  args: ^0.13.5
  browser: ^0.10.0+2
  gtag_analytics: ^0.1.5
  html: ^0.12.2+2
  logging: ^0.11.3
  markdown: ^0.10.1
  path: ^1.3.9
  resource: ^1.1.0
  slot_machine:
    path: ../slot_machine
  test: ^0.12.15+3
  watcher: ^0.9.7+3

dev_dependencies:
  a_star: ^0.3.0

executables:
  egamebook:
