name: egamebook
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  a_star: '>=0.3.0 <0.4.0'
  analyzer: '>=0.23.0 <0.26.0'
  args: '>=0.12.1 <0.13.0'
  browser: '>=0.10.0+2 <0.11.0'
  html5lib: '>=0.10.0 <0.11.0'
  jsonml: '>=0.1.1 <0.2.0'
  markdown: '>=0.7.0 <0.8.0'
  path: '>=1.1.0 <2.0.0'
  unittest: "0.12.2"
  watcher: ">=0.9.5 <0.10.0"
executables:
  egamebook:
