name: egamebook
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  path: any
  browser: any
  unittest: any
  args: any
  a_star: any
#  markdown: any
#  graphml:
#    git: https://github.com/filiph/dart-graphml.git
