name: egamebook
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  browser: any
  unittest: 0.4.7+1
  args: any
#  markdown: any
#  graphml:
#    git: https://github.com/filiph/dart-graphml.git
