name: egamebook
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  browser: any
  unittest:
    sdk: unittest
  graphml:
    git: https://github.com/filiph/dart-graphml.git
  args:
    sdk: args
