name: egamebook
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  html5lib: ">=0.10.0 <0.11.0"
  jsonml: ">=0.1.1 <0.2.0"
  path: ">=1.1.0 <1.2.0"
  browser: ">=0.10.0+2 <0.11.0"
  unittest: ">=0.10.1+2 <0.11.0"
  args: ">=0.10.0+2 <0.11.0"
  a_star: ">=0.3.0 <0.4.0"
  markdown: ">=0.7.0 <0.8.0"
#  markdown:
#    git: https://github.com/filiph/dart-markdown.git
#  graphml:
#    git: https://github.com/filiph/dart-graphml.git
