dart:
  - stable

stages:
  - smoke_test:
    - description: "dartfmt && dartanalyzer"
      group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - group:
      - command: pub run test

cache:
  directories:
    - .dart_tool/build
