# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  gather_builder:
    import: "package:egamebook_builder/gather_builder.dart"
    builder_factories: ["gatherBuilder"]
    build_extensions: {"_gather.dart": [".gathered.dart"]}
    build_to: source
    auto_apply: dependents
    required_inputs:
      # Makes sure that built_value generation has already been performed
      # by the time this builder runs. Otherwise, the `*_gather.dart` source
      # can fail to statically analyze, and no instances will be gathered.
      - '.g.dart'
    defaults:
      generate_for:
        - '**/*_gather.dart'

  writers_builder:
    import: "package:egamebook_builder/writers_builder.dart"
    builder_factories: ["writersBuilder"]
    build_extensions: {".dart": [".compiled.dart"]}
    build_to: source
    auto_apply: none
    runs_before:
      - 'built_value_generator|built_value'
