name: egamebook_builder
description: Builders for egamebook.
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^0.12.7
  built_value: ^5.1.0
  code_builder: ^3.1.2
  dart_style: ^1.1.3
  glob: ^1.1.7
  source_gen: ^0.8.0

dependency_overrides:
  analyzer_plugin: ^0.0.1-alpha.4

dev_dependencies:
  test: ^1.0.0
